#INITIAL SETTINGS -example
data_directory: ../data/
data_name: breast-cancer-wisconsin.data
drop_columns: ["id"]
target_name: class
test_size: 0.2
model_directory: ../models/
model_name: KNN_classifier.pkl

# gemini config
